# docker-compose.yml

version: "3.8"

services:
  # バックエンド（Spring Boot）の設定
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    user: root
    container_name: todo-backend-container
    ports:
      - "8080:8080" # ← バックエンドのポート
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todo_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./backend:/app
    command: sleep infinity # ←【変更点3】CMDではなくcommandで上書き
    depends_on:
      - db
    restart: "no" # 開発中は手動で制御することが多いので明示的にOFF

  # フロントエンド（Next.js）の設定
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend-container
    ports:
      # 3000番のポートをコンテナの3000番ポートに接続
      - "3000:3000"
    volumes:
      - ./frontend:/app
      #- /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    restart: "no" # 開発中は手動で制御することが多いので明示的にOFF

  # データベース (PostgreSQL) の設定
  db:
    image: postgres:14
    container_name: todo-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data # データの永続化

  # pgAdminの設定
  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin-container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped

# データの永続化設定
volumes:
  db-data:
  pgadmin_data:
